version: '3.9'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: nginx
      args:
        #DEV_MODE: compose
        DEV_MODE: develop
        #DEV_MODE: prod
    ports:
      - "80:8080"
    environment:
      ENVSUBST: $\{NGINX_PORT\} $\{FASTAPI_ENDPOINT\} $\{FASTAPI_PORT\} $\{VUE_ENDPOINT\} $\{VUE_PORT\}
    depends_on:
      fastapi:
        condition: service_healthy
      vue:
        condition: service_healthy
  vue:
    hostname: vue
    deploy:
      replicas: 2
    build:
      context: vue
      args:
        #DEV_MODE: compose
        DEV_MODE: develop
        #DEV_MODE: prod
    healthcheck:
      test: curl --fail http://localhost:$${VUE_PORT} || exit 1
      start_period: 10s
      interval: 1s
      retries: 3
      timeout: 1s
    volumes:
      - ${PWD}/vue/src:/app/src:rw
  fastapi:
    hostname: fastapi
    deploy:
      replicas: 2
    build:
      context: fastapi
      args:
        #DEV_MODE: compose
        DEV_MODE: develop
        #DEV_MODE: prod
    restart: always
    healthcheck:
      test: curl --fail http://localhost:$${UVICORN_PORT}/healthz || exit 1
      start_period: 1s
      interval: 1s
      retries: 2
      timeout: 1s
    volumes:
      - ${PWD}/fastapi/src/:/app/src
  redis:
    hostname: redis
    container_name: redis
    build:
      context: redis
